### ISSUE TITLE
issue with 8.1.diff

### ISSUE THREAD

**Issue by palxex** [zinglau/obfuscated-openssh-patches#12]
the *.orig part should not exist in patch.
https://raw.githubusercontent.com/palxex/homebrew-obfuscated-openssh/master/patches/8.1.diff
Tried create a clean version, 5% size and same behaviour, if I didn't make anything wrong:) please verify it.

**Comment by zinglau** [comment]
Thanks for the heads-up. Fixed now. https://github.com/zinglau/obfuscated-openssh-patches/commit/85f48ff622c705b9fa571dadfb9737c1524a0794
