### ISSUE TITLE
Ubuntu PPA not updated with package for 17.10 (artful)

### ISSUE THREAD

**Issue by LiaungYip** [zinglau/obfuscated-openssh-patches#7]
The [Launchpad / Ubuntu PPA](https://launchpad.net/~zinglau/+archive/ubuntu/obfuscated-openssh/+packages) has not yet been updated with a binary package for Ubuntu 17.10 `artful`.

It would be greatly appreciated if the PPA could be updated.

Thanks kindly for your maintenance of this utility!

**Comment by zinglau** [comment]
uploaded, pls test.
